Fix docker tag typo

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,6 +24,10 @@ jobs:
 
       - name: Build and Push Image
         run: |
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest .
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest
-          #
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+          echo "DOCKERHUB_USERNAME secret is missing"
+          exit 1
+        fi
+
+        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest .
+        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest
