Fix docker CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,9 +25,9 @@ jobs:
       - name: Build and Push Image
         run: |
           if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
-          echo "DOCKERHUB_USERNAME secret is missing"
-          exit 1
-        fi
+            echo "DOCKERHUB_USERNAME secret is missing"
+            exit 1
+          fi
 
-        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest .
-        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest .
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-sqlite-app:latest
